# GitHub Sponsors configuration for emotion-analysis-indischool
# 초등교사 커뮤니티 감정분석 시스템 후원 설정

# GitHub Sponsors (primary)
github: rubato103

# Alternative funding platforms (예시 - 실제 계정으로 교체 필요)
# ko_fi: yangdong  # Ko-fi 계정명
# patreon: yangdong  # Patreon 계정명
# paypal: yangdong  # PayPal.me 링크

# Custom funding URLs
# custom: ['https://toss.me/yangdong', 'https://www.buymeacoffee.com/yangdong']

# Note: 위 계정들은 예시입니다. 실제 후원 계정으로 수정해주세요.